#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

function usage() {
  local -i exitval=${1-1}
  cat << USAGE
usage: $(basename "${BASH_SOURCE[0]}") [-h] [--suffix SUFFIX]

Validates project by building it, verifying checksums, and running all tests.
This is done inside the container and on the host.

options:
  -h, --help            Show this help message and exit.
  --suffix SUFFIX       Image suffix.
USAGE
  exit ${exitval}
}

declare SUFFIX=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --suffix)
      SUFFIX="$2"
      shift 2 || usage
      ;;
    -h | --help) usage 0 ;;
    *)
      printf "unrecognized arg: %s\n" "$1"
      usage
      ;;
  esac
done

"devkit/build${SUFFIX}" "./ci/test_entrypoint"
{% if toolchain == "llvm_custom_sysroot" -%}
devkit/coverage --line 100 --branch 100
{% endif -%}
{% if toolchain == "llvm_bootstrapped" -%}
devkit/bep
{% endif -%}
# This might fail if Bazel is not installed
"./ci/test_entrypoint" || true
