#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

SCRIPTS="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
readonly SCRIPTS
source "${SCRIPTS}/lib_logging.sh"
declare -r IMAGES="${SCRIPTS}/../images"

DEVKIT_CONFIG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      DEVKIT_CONFIG="$2"
      shift 2
      ;;
    *)
      break
      ;;
  esac
done

declare -r IMAGE_NAME="$1"
shift

if [[ -z "${DEVKIT_CONFIG}" ]]; then
  DEVKIT_CONFIG="$("${SCRIPTS}/uv" "${SCRIPTS}/find_project_root.py")/devkit.json"
fi
readonly DEVKIT_CONFIG

BUILD_CMD="${SCRIPTS}/uv ${SCRIPTS}/docker/build.py ${IMAGE_NAME} --print-tag --search-path ${IMAGES} --log-file ${DEVKIT_LOG_FILE} --config ${DEVKIT_CONFIG}"
readonly BUILD_CMD

IMAGE_URI="$(${BUILD_CMD})" || {
  echo "Build failed. See logs for details: ${DEVKIT_LOG_FILE}" >&2
  exit 1
}
readonly IMAGE_URI

"${SCRIPTS}/docker_run.py" --devkit-log-file "${DEVKIT_LOG_FILE}" "${IMAGE_URI}" "$@"
