#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

DEVKIT="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
readonly DEVKIT

readonly SCRIPTS="${DEVKIT}/../scripts"
readonly IMAGES="${DEVKIT}/../images"

source "${SCRIPTS}/lib_logging.sh"

PROJECT_ROOT="$("${SCRIPTS}/uv" "${SCRIPTS}/find_project_root.py")"
readonly PROJECT_ROOT

VSCODE_SERVER_IMAGE="$("${SCRIPTS}/uv" "${SCRIPTS}/docker/build.py" vscode-server --print-tag --search-path "${IMAGES}" --log-file "${DEVKIT_LOG_FILE}" --config "${PROJECT_ROOT}/devkit.json")" || {
  echo "Build failed. See logs for details: ${DEVKIT_LOG_FILE}" >&2
  exit 1
}
readonly VSCODE_SERVER_IMAGE

declare -r CODE_SERVER_CONFIG_HOME="${HOME}/.config/code-server"
declare -r CODE_SERVER_SHARE_LOCAL_HOME="${HOME}/.local/share/code-server"
declare -r MICROSOFT_CACHE_HOME="${HOME}/.cache/Microsoft"
declare -r GOOGLE_VSCODE_EXTENSION_CACHE_HOME="${HOME}/.cache/google-vscode-extension"
declare -r CLOUD_CODE_CACHE_HOME="${HOME}/.cache/cloud-code"

mkdir -p "${CODE_SERVER_CONFIG_HOME}"
mkdir -p "${CODE_SERVER_SHARE_LOCAL_HOME}"
mkdir -p "${MICROSOFT_CACHE_HOME}"
mkdir -p "${GOOGLE_VSCODE_EXTENSION_CACHE_HOME}"
mkdir -p "${CLOUD_CODE_CACHE_HOME}"

"${SCRIPTS}/docker_run.py" \
  --devkit-log-file "${DEVKIT_LOG_FILE}" \
  "--volume=${CODE_SERVER_CONFIG_HOME}:${CODE_SERVER_CONFIG_HOME}" \
  "--volume=${CODE_SERVER_SHARE_LOCAL_HOME}:${CODE_SERVER_SHARE_LOCAL_HOME}" \
  "--volume=${MICROSOFT_CACHE_HOME}:${MICROSOFT_CACHE_HOME}" \
  "--volume=${GOOGLE_VSCODE_EXTENSION_CACHE_HOME}:${GOOGLE_VSCODE_EXTENSION_CACHE_HOME}" \
  "--volume=${CLOUD_CODE_CACHE_HOME}:${CLOUD_CODE_CACHE_HOME}" \
  "${VSCODE_SERVER_IMAGE}" \
  code-server --auth=none "$@" "${PWD}"
