#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o xtrace
export TZ=Etc/UTC
export PS4='+\t $(basename ${BASH_SOURCE[0]}):${LINENO} ' # xtrace prompt

function collect_logs() {
  if [[ -v KOKORO_ARTIFACTS_DIR ]]; then
    cp -r "${HOME}/.devkit/logs" "${KOKORO_ARTIFACTS_DIR}"
  fi
}
trap collect_logs EXIT

declare -i DEBUG=0
declare -a FLAGS=()

function usage() {
  local -i exitval=${1-1}
  cat <<USAGE
usage:
  $0 <options>
    --debug                    run in debug mode
USAGE
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --debug)
      DEBUG=1
      FLAGS+=(--debug)
      shift
      ;;
    -h | --help) usage 0 ;;
    *)
      printf "unrecognized arg: %s\n" "$1"
      usage
      ;;
  esac
done

if [[ -n "${KOKORO_ARTIFACTS_DIR:-}" ]]; then
  cd "${KOKORO_ARTIFACTS_DIR}/git/devkit"
fi

devkit/pre-commit
devkit/gitlint --debug run-hook

tools/ci/utils/build_docs "${FLAGS[@]}"
tools/ci/utils/test_devkit_docker_run_args.sh
tools/ci/utils/test_devkit_get_architecture.sh
tools/ci/utils/test_devkit_stdin.sh
tools/ci/utils/test_devkit_execute_in_subdirectories.sh
tools/ci/utils/test_devkit_json_docker_run_args.sh
tools/ci/utils/test_devkit_vendor.sh
tools/ci/utils/test_devkit_check_checksums.sh
tools/ci/utils/test_devkit_gitlinks.sh

readonly DEVKIT="${PWD}"

declare -i num_templates
num_templates=$(grep -E -c -v '^[[:space:]]*($|#)' "${DEVKIT}/templates.txt")
declare -i counter=0

# We are using file descriptor 3 to read the templates, so that the commands
# executed inside the loop do not consume the input from the file.
while IFS= read -r -u 3 template_args || [[ -n "${template_args}" ]]; do
  if [[ -z ${template_args} ]] || [[ ${template_args} =~ ^# ]] ; then
    continue
  fi
  counter+=1

  declare WORKSPACE=/tmp/workspace
  if [[ ${DEBUG} -ne 1 ]]; then
    WORKSPACE="$(mktemp --directory)"
  fi

  function template_cleanup() {
    if [[ ${DEBUG} -ne 1 ]]; then
      rm -rf "${WORKSPACE}"
    fi
  }
  rm -rf "${WORKSPACE}"
  mkdir -p "${WORKSPACE}"
  trap template_cleanup RETURN

  cd "${WORKSPACE}"

  ln -s "${DEVKIT}" "${WORKSPACE}/.devkit"
  ln -s .devkit/devkit devkit

  # shellcheck disable=SC2086
  devkit/bootstrap ${template_args}

  # Commit the code, so the pre-commit can be executed.
  git init
  git add .
  git commit -m "chore: Initial commit" -m "Setting-up a test repo."

  devkit/pre-commit
  devkit/gitlint --debug run-hook

  if [[ -n "$(git status --porcelain)" ]]; then
    echo "Unexpected git change in the instantiated template. Add them to the template."
    git diff
    exit 1
  fi

done 3< "${DEVKIT}/templates.txt"

if [[ ${counter} -ne ${num_templates} ]]; then
  echo "error: The number of processed templates (${counter}) does not match the number of templates in templates.txt (${num_templates})." >&2
  exit 1
fi
