/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.kmsclient;

import com.google.auto.value.AutoValue;

/** Represents a key generated by a KMS. */
@AutoValue
public abstract class KmsGeneratedKey {

  public static Builder builder() {
    return new AutoValue_KmsGeneratedKey.Builder();
  }

  /** The plaintext key material. */
  public abstract byte[] plaintext();

  /** The key material encrypted by the KMS master key. */
  public abstract byte[] ciphertext();

  /** Builder for {@link KmsGeneratedKey}. */
  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setPlaintext(byte[] value);

    public abstract Builder setCiphertext(byte[] value);

    public abstract KmsGeneratedKey build();
  }
}
