policies {
  key: "policy1"
  value {
    publisher_id: "pub-invalid"
    workload_id: "work-invalid"
    trust_domain: "invalid.org"
    # missing attributes in toDomain(Policies) results in filtering,
    # but having attributes and an empty reference_values oneof
    # triggers the exception in ReferenceValuesType toDomain.
    certificate_attributes {
      max_certificate_validity {
        seconds: 3600
      }
    }
    reference_values {
      oak_reference_values {
        oak_containers: {
          root_layer: {
            insecure: { }
          }
          kernel_layer: {
            kernel: {
              endorsement: {
                rekor: {
                  skip: { }
                }
              }
            }
            kernel_cmd_line_text: {
              skip: { }
            }
            init_ram_fs: {
              skip: { }
            }
            memory_map: {
              skip: { }
            }
            acpi: {
              skip: { }
            }
          }
          system_layer: {
            system_image: {
              skip: { }
            }
          }
          container_layer: {
            binary: {
              skip: { }
            }
            configuration: {
              skip: { }
            }
          }
        }
      }
    }
  }
}

policies {
  key: "policy2"
  value {
    publisher_id: "pub-invalid"
    workload_id: "work-invalid"
    trust_domain: "invalid.org"
    certificate_attributes {
      max_certificate_validity {
        seconds: 3600
      }
    }
    reference_values {
      # Empty reference_values
    }
  }
}

policies {
  key: "policy3"
  value {
    publisher_id: "pub-invalid"
    workload_id: "work-invalid"
    trust_domain: "invalid.org"
    certificate_attributes {
      max_certificate_validity {
        seconds: 3600
      }
    }
    reference_values {
      oak_reference_values {
        oak_containers: {
          root_layer: {
            insecure: { }
          }
          kernel_layer: {
            kernel: {
              endorsement: {
                rekor: {
                  skip: { }
                }
              }
            }
            kernel_cmd_line_text: {
              skip: { }
            }
            init_ram_fs: {
              skip: { }
            }
            memory_map: {
              skip: { }
            }
            acpi: {
              skip: { }
            }
          }
          system_layer: {
            system_image: {
              skip: { }
            }
          }
          container_layer: {
            binary: {
              skip: { }
            }
            configuration: {
              skip: { }
            }
          }
        }
      }
    }
  }
}
