policies {
  key: "test-policy"
  value {
    publisher_id: "publisher-1"
    workload_id: "workload-1"
    trust_domain: "example.org"
    certificate_attributes {
      max_certificate_validity {
        seconds: 3600
      }
      x509_extensions {
        basic_constraints {
          ca_certificate {
            path_len_constraint: 1
          }
        }
        name_constraints {
          permitted_subtree: ".example1.org"
          permitted_subtree: ".example2.org"
        }
      }
    }
    reference_values {
      oak_reference_values {
        oak_containers: {
          root_layer: {
            insecure: { }
          }
          kernel_layer: {
            kernel: {
              endorsement: {
                rekor: {
                  skip: { }
                }
              }
            }
            kernel_cmd_line_text: {
              skip: { }
            }
            init_ram_fs: {
              skip: { }
            }
            memory_map: {
              skip: { }
            }
            acpi: {
              skip: { }
            }
          }
          system_layer: {
            system_image: {
              skip: { }
            }
          }
          container_layer: {
            binary: {
              skip: { }
            }
            configuration: {
              skip: { }
            }
          }
        }
      }
    }
    reference_values {
      oak_reference_values {
        oak_containers: {
          root_layer: {
            insecure: { }
          }
          kernel_layer: {
            kernel: {
              endorsement: {
                rekor: {
                  skip: { }
                }
              }
            }
            kernel_cmd_line_text: {
              skip: { }
            }
            init_ram_fs: {
              skip: { }
            }
            memory_map: {
              skip: { }
            }
            acpi: {
              skip: { }
            }
          }
          system_layer: {
            system_image: {
              skip: { }
            }
          }
          container_layer: {
            binary: {
              skip: { }
            }
            configuration: {
              skip: { }
            }
          }
        }
      }
    }
  }
}
policies {
  key: "test-policy-2"
  value {
    publisher_id: "publisher-2"
    workload_id: "workload-2"
    trust_domain: "example.com"
    reference_values {
      oak_reference_values {
        oak_containers: {
          root_layer: {
            insecure: { }
          }
          kernel_layer: {
            kernel: {
              endorsement: {
                rekor: {
                  skip: { }
                }
              }
            }
            kernel_cmd_line_text: {
              skip: { }
            }
            init_ram_fs: {
              skip: { }
            }
            memory_map: {
              skip: { }
            }
            acpi: {
              skip: { }
            }
          }
          system_layer: {
            system_image: {
              skip: { }
            }
          }
          container_layer: {
            binary: {
              skip: { }
            }
            configuration: {
              skip: { }
            }
          }
        }
      }
    }
    certificate_attributes {
      max_certificate_validity {
        seconds: 720
      }
      x509_extensions {
        basic_constraints {
          ca_certificate {
            path_len_constraint: 1
          }
        }
        name_constraints {
          permitted_subtree: ".example2.org"
        }
      }
    }
  }
}
