# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Macros for building AWS enclave images and VM AMIs."""

load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("//build_defs/aws/enclave:container.bzl", "java_enclave_image")
load("//build_defs/aws/enclave:enclave_watcher_rpm.bzl", "enclave_watcher_rpm")
load("//operator/worker/aws/build_defs:ami.bzl", "packer_worker_ami")

def aws_eif_and_ami(
        *,
        name,
        ami_name,
        ami_groups = "[]",
        packer_ami_config = Label("//build_defs/aws/enclave:pcit_enclave_ami.pkr.hcl"),
        ec2_instance = "m5.xlarge",
        subnet_id,
        enclave_cpus = 2,
        enclave_memory_mib = 7168,
        aws_region,
        enclave_env_variables = {},
        enclave_cmd = [],
        jar_path,
        proxy_rpm = "@rules_aws//cc/aws/proxy:vsockproxy_rpm",
        watcher_rpm = None,
        startup_script = Label("//build_defs/aws/enclave:setup_enclave.sh"),
        service_name = "enclave",
        jar_file = None,
        jar_args = [],
        jvm_options = [],
        licenses = [],
        enable_worker_debug_mode = False,
        uninstall_ssh_server = True,
        user_rpms = [],
        additional_container_files = [],
        additional_container_tars = []):
    """Creates targets for AWS AMI generation and enclave Docker container for PCIT services.

    Assuming the name passed is 'pcit_instance', this macro instantiates multiple
    targets:
      1. calls container_image macro with name 'pcit_instance_container': check the
         documentation for container_image macro for details what targets are
         available; notable targets are 'pcit_instance_container' which represent the
         layer for the Docker image, as well as 'pcit_instance_container.tar' which is
         the complete tar archive containing the full Docker image
      2. 'pcit_instance': executable target which downloads Packer and runs it to
         prepare the AMI image containing the proxy, proxy configuration and is
         ready to run the enclave upon startup.

    Args:
      name: The target name used to generate the targets described above.
      ami_name: Path to a `string_flag` target defining the name of the AMI that
        is generated by the target.
      ami_groups: Groups to share AMI with. Default is none. Change to ["all"]
        to make AMI public.
      packer_ami_config: Path to the packer config template.
      ec2_instance: Ec2 instance type for running packer script.
      subnet_id: Path to a `string_flag` target defining the subnet in which to
        deploy the EC2 instance to execute the packer scripts.
      enclave_cpus: Number of cores assigned to enclave.
      enclave_memory_mib: Amount of memory (in MB) assigned to enclave.
      aws_region: Path to a `string_flag` target defining the AWS region to run the
        packer script in.
      enclave_env_variables: Dict (string-to-string) of environment variables to
        be added to the enclave.
      enclave_cmd: Command (in exec form) to start up the enclave container.
      jar_path: Path to deployable jar.
      proxy_rpm: Path to proxy rpm.
      watcher_rpm: Path to watcher rpm. If not provided, a default watcher RPM will be generated.
      jar_file: Absolute path to the JAR file in the enclave that should be
        invoked.
      jar_args: CLI args passed to the JAR file inside the enclave.
      jvm_options: Jvm options passed to control JVM inside the enclave.
      licenses: A list of labels of tar files containing the licenses
        of our distribution and all dependencies.
      enable_worker_debug_mode: Whether to run enclave in debug mode.
      uninstall_ssh_server: Whether to uninstall SSH server from AMI once
        provisioning is completed.
      user_rpms: A list of other RPMs to install on the AMI.
      additional_container_files: A list of additional files to be included in the container.
      startup_script: path to a startup script
      service_name: The name of the service used for isolation and naming.
      additional_container_tars: Additional tars that will be passed to the java_enclave_image.
    """

    docker_target_name = "%s_container" % name

    # Build target for the Docker container
    java_enclave_image(
        name = docker_target_name,
        jar_target = jar_path,
        jar_filename = jar_file,
        jar_args = jar_args,
        jvm_options = jvm_options,
        enclave_cmd_override = enclave_cmd,
        enclave_env_variables = enclave_env_variables,
        additional_files = additional_container_files,
        additional_tars = additional_container_tars,
    )

    merged_licenses_name = "%s_merged_licenses" % name
    pkg_tar(
        name = merged_licenses_name,
        deps = [Label("@rules_aws//licenses:licenses_tar")] + licenses,
    )

    if not watcher_rpm:
        enclave_watcher_rpm(
            name = name + "_watcher_rpm",
            service_name = service_name,
        )
        watcher_rpm = ":" + name + "_watcher_rpm"

    # Executable target for running Packer to generate the complete AMI image
    packer_worker_ami(
        name = name,
        enclave_container_image = ":%s.tar" % docker_target_name,
        proxy_rpm = proxy_rpm,
        worker_watcher_rpm = watcher_rpm,
        packer_ami_config = packer_ami_config,
        ami_name = ami_name,
        ami_groups = ami_groups,
        ec2_instance = ec2_instance,
        subnet_id = subnet_id,
        enclave_cpus = enclave_cpus,
        enclave_memory_mib = enclave_memory_mib,
        aws_region = aws_region,
        enable_worker_debug_mode = enable_worker_debug_mode,
        uninstall_ssh_server = uninstall_ssh_server,
        licenses = ":" + merged_licenses_name,
        user_rpms = user_rpms,
        startup_script = startup_script,
    )
